//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFS_officesmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAdmin
    {
        public System.Guid AdminID { get; set; }
        public System.Guid RoleID { get; set; }
        public Nullable<System.Guid> Reserved { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string IDCode { get; set; }
        public Nullable<System.Guid> EUID { get; set; }
        public string Wxid { get; set; }
    }
}
