//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFS_officesmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSysMenu
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public string MenuURL { get; set; }
        public Nullable<int> MenuPartNo { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<int> Menusort { get; set; }
    }
}
