//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFS_officesmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tUser
    {
        public int UserID { get; set; }
        [Display(Name = "用户名")]
        [MaxLength(12, ErrorMessage = "太长了")]
        public string UserName { get; set; }
        [Display(Name = "密码")]
        public string PassWord { get; set; }
    }
}
