//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFS_officesmart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_BFSEntities : DbContext
    {
        public db_BFSEntities()
            : base("name=db_BFSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAdmin> tAdmin { get; set; }
        public virtual DbSet<tRole> tRole { get; set; }
        public virtual DbSet<tRoleMenu> tRoleMenu { get; set; }
        public virtual DbSet<tSmartRole> tSmartRole { get; set; }
        public virtual DbSet<tSysMenu> tSysMenu { get; set; }
    }
}
